spring:
  profiles:
    active: dev
  #  限制上传文件大小 MB必须大写
  #  maxFileSize 是单个文件大小
  #  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

# mybatis开启驼峰命名自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true