spring:
  datasource:
    druid:
      url: jdbc:mysql://120.48.48.246:33306/multithreading?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yiwang2023

# mybatis-plus
mybatis-plus:
  configuration:
    # SQL打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl